# Generated by Django 5.1 on 2024-09-10 21:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='mail',
            field=models.EmailField(default=users.models.User, max_length=254, verbose_name='Email'),
        ),
    ]
