# Generated by Django 5.1 on 2024-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_books', '0002_alter_addbook_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
