# Generated by Django 5.1 on 2024-09-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_books', '0003_alter_addbook_is_published_alter_addbook_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbook',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложение'},
        ),
    ]
