# Generated by Django 5.1 on 2024-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='no-avatar.jpg', null=True, upload_to='users/images/', verbose_name='Фото профиля'),
        ),
    ]
