# Generated by Django 5.1 on 2024-09-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create'], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
    ]
