# Generated by Django 5.1 on 2024-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.TextField(blank=True),
        ),
    ]
