# Generated by Django 5.1 on 2024-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.TextField(blank=True, verbose_name='Источник'),
        ),
    ]
