# Generated by Django 5.1 on 2024-09-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialitem',
            options={'verbose_name': 'Соц сеть', 'verbose_name_plural': 'Соц сети'},
        ),
    ]
