# Generated by Django 5.0.2 on 2024-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_rating_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_book',
            field=models.FileField(blank=True, upload_to='download', verbose_name='скачать'),
        ),
    ]
